# Generated by Django 4.1.7 on 2023-03-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='book_id',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='writer_name',
            new_name='writer',
        ),
    ]
